# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PushNotification' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushNotification
  pod 'FirebaseMessaging'
  pod 'Firebase/Core'

  target 'PushNotification-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PushNotificationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PushNotification-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PushNotification-tvOS

end
